### PR TITLE
feat: relations

### LINKED ISSUE #15: Replace Promises with RxJS Observables

### LINKED ISSUE #22: Should we really use JSON Schema ?
No preference here, just some thoughts :)
It could be best to define object at compile time.
Should we act as a high level language like Java or Scala by defining DAO's and Objects statically (example: HeroResource, HeroRecord).
Or should we use some shema to define what we're expecting and only type DAO's statically (example: heroSchema describe a specific type of schema, a hero resource is defined with a schema) ?
@firehist

### LINKED ISSUE #24: Relations
Implements relations in resources & records.
Some examples :
 - [JSData](http://www.js-data.io/docs/home)
 - [SailsJS](http://sailsjs.org/documentation/concepts/models-and-orm)

### PR DESCRIPTION
**Pull request by nimaen**
Also includes :

- feat: replace rxjs with promises
- feat: add coveralls
- feat: remove json schema with a custom implementation

Related to https://github.com/Elium/mighty-http-adapter/pull/3

It resolves #15, resolves #24, closes #22.

### CODE REVIEW

**Comment by heiso** [comment]
Relations shouldn't you keep it simple ? :p

**Comment by nimaen** [comment]
Which part is complicated ? 💃 
It's true that the PR does reflect too much changes unrelated to relations...

**Comment by heiso** [comment]
Didn't read the code, I was just talking about your decision to not implement relation in your lib to avoid complicated behaviors :p

**Comment by nimaen** [comment]
What are you talking about 😄  ? I DID implement relations...

**Comment by firehist** [comment]
💤

**Comment by heiso** [comment]
Graaaaaouuuuuuu 🐻

**Comment by nimaen** [comment]
I don't... know. What... do... you... call... a... three-humped... camel 🐫

**Pull request merged**
